spring:
  application:
    name: MatchMyTier

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 84760649084-9cd7ondh0ukuj5ko901hbfirda3ouf7j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile