spring:
  application:
    name: Project_2

  datasource:
    username: g352x3hlhb5kad1i
    password: uhxea8jepzksh1xz
    url: jdbc:mysql://thzz882efnak0xod.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/b4549h5xz4s1t6pf
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 84760649084-9cd7ondh0ukuj5ko901hbfirda3ouf7j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile